<a href="https://colab.research.google.com/github/21pa1a6128/DWM-lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [16]:
x=np.array([1,2,3,4])

In [17]:
x

array([1, 2, 3, 4])

In [18]:
y=np.append(x,[5,6,7])
y

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
x=np.delete(x,1)
x

array([2, 3, 4])

In [21]:
x=np.append(1,x)
x

array([1, 1, 2, 3, 4])

In [23]:
arr=np.arange(0,50,10)
arr

array([ 0, 10, 20, 30, 40])

In [24]:
arr[arr<20]=50

In [25]:
arr

array([50, 50, 20, 30, 40])

In [30]:
print(x)
print(y)
print(arr)
print("x plus arr",x+arr)
# print("y plus arr",y+arr) both numpy lists shape must be equal to perfom this operation

[1 1 2 3 4]
[1 2 3 4 5 6 7]
[50 50 20 30 40]
x plus arr [51 51 22 33 44]


In [40]:
# slicing 2d arrays
arr1=np.arange(1,13)
arr1=arr1.reshape(4,3)
print(arr1)
arr1[1:4]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr1.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])