<a href="https://colab.research.google.com/github/21pa1a6128/DWM-lab/blob/main/operations_on_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/students_placement_data.csv')

In [7]:
#Q1 basic characteristics of the data

df.describe()

Roll No  SSC Percentage  inter_Diploma_percentage  \
count  117.000000      116.000000                117.000000   
mean    59.000000       80.153362                 80.535299   
std     33.919021        9.462320                 11.818567   
min      1.000000       44.000000                 40.200000   
25%     30.000000       75.875000                 73.400000   
50%     59.000000       82.745000                 83.600000   
75%     88.000000       87.025000                 90.000000   
max    117.000000       93.660000                 96.900000   

       B.Tech_percentage    Backlogs  
count         116.000000  117.000000  
mean           62.662672    4.111111  
std            12.591167    6.335148  
min            21.200000    0.000000  
25%            54.175000    0.000000  
50%            63.885000    0.000000  
75%            72.570000    7.000000  
max            88.100000   25.000000

In [ ]:
# Q2 check if there is any missing value in dataset
df.isna().any()

In [57]:
#Q3 finding mean of the SSC Percentage without using mean function

df_series=df['SSC Percentage']
j=0
t=0
li=df_series.isna()
for i,na in zip(df_series,range(len(li))):
  if(not li[na]):
    j+=i
  else:t+=1
print('mean of the SCC Percentage',j/(len(li)-t))

mean of the SCC Percentage 80.1533620689655


In [82]:
#Q5 replacing null values with mean
df['SSC Percentage'].fillna(df['SSC Percentage'].mean(),inplace=True)
df['B.Tech_percentage'].fillna(df['B.Tech_percentage'].mean(),inplace=True)
df['registered_for_ Placement_Training'].fillna(df['registered_for_ Placement_Training'].mode()[0],inplace=True)
df.isna().any()

Roll No                               False
Gender                                False
Section                               False
SSC Percentage                        False
inter_Diploma_percentage              False
B.Tech_percentage                     False
Backlogs                              False
registered_for_ Placement_Training    False
placement status                      False
dtype: bool

In [84]:
#Q4 plot a scatter plot between SCC Percentage and intermediate percentage
import matplotlib.pyplot as plt


SyntaxError: ignored

In [89]:
li=np.arange(1,7)
print(li)
li=li.reshape(2,3)
print(li)
print(li[-1,-1])
print(li[1,1])
li.T

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
6
5


array([[1, 4],
       [2, 5],
       [3, 6]])